### ISSUE TITLE
Using Authentication with HTTPS - status 500 error

### ISSUE THREAD

**Issue by bucktaylor** [nolanlawson/pouchdb-authentication#50] opened 2015-08-18 13:06 UTC
I am getting a status 500 error when I try to login using the authentication plugin over https on port 6984 from an external IP to my public domain address. I am using a self-signed certificate.

I have CORS set up, but get the following message: 

CustomPouchError {status: 500, name: "unknown_error", message: "Database encountered an unknown error Unknown error!  Did you remember to enable CORS?", error: true}

I can login if I go directly to the server from within my network using its machine IP address (.ie. 192.168.XXX.XXX).

I have no problem logging in over http on port 5984 over the same public domain.

I can also login to Futon using https at the same public address that fails above - so the SSL certificate works for Couchdb.

I put Pouchdb into debug mode, but I really can't see anything that helps.

Any thoughts where I should look?

**Comment by nolanlawson** [comment] 2015-08-23 19:27
Hm, do you have a proxy set up between your app and CouchDB? This sounds like a CORS issue, and I'm wondering if all the CORS headers aren't being passed through properly by the proxy.

CouchDB has some instructions for setting up an Nginx proxy: https://wiki.apache.org/couchdb/Nginx_As_a_Reverse_Proxy

**Comment by bucktaylor** [comment] 2015-08-25 20:43
@nolanlawson  - I posted over in the pouchdb git as well: "Unkown error during authentication #4175"

I do not have a proxy set up (although I thought about doing so).

The immediate solution is to pay for a trusted certificate. Basically the browser is stopping the transaction with the SSL warning - so pouchdb doesn't currently have a way to deal with this.

Thanks

**Comment by nolanlawson** [comment] 2015-08-26 03:20
Hm, it could be because we call `withCredentials = true` on the XMLHttpRequest object? You could try removing that and see if it helps. I admit I'm not too familiar with SSL stuff. :/

**Comment by mnewmedia** [comment] 2015-12-14 15:55
I'm just throwing in, what I had.

Using self signed certificate, it works in the all browsers via `basic authentication and cookie authentication`. 
*`cordova and basic authentication` all posts will fail
*`cordova and cookie authentication` all posts and get will fail

Maybe i find it somewhen out, but consider using a free ssl certificate from `lets encrypt`.

**Comment by singhketan** [comment] 2015-12-16 15:42
I am reviving one of my older projects right now which used to work well as of July this year. I have installed the latest version of couchDB, but now the app doesn't work. It throws a 500, and suggests that I have CORS enabled. I have enabled CORS though.

What should I do?

**Comment by nolanlawson** [comment] 2015-12-17 00:35
@singhketan You mean you upgraded CouchDB or PouchDB? Or both?

To be honest I haven't looked into this in a long while, and I welcome anybody to investigate it themselves and try to fix it. This repo is only a few hundred lines of code.

**Comment by nolanlawson** [comment] 2015-12-17 00:35
I also am not sure how to reproduce, because the tests all still pass for me.

**Comment by bucktaylor** [comment] 2015-12-17 23:22
Guess what - now I'm getting this error too! 

I updated and restarted Ubuntu server yesterday, now it is throwing this error. Was working fine yesterday prior to server update - no changes to any of my code. I am using a real certificate (which solved the problem initially). I can log into Couch through Futon through the HTTP connection, but Pouch throws an error (status 500) when trying to log in....

@nolanlawson - can you point me to where in the code I should start looking. Seems to me its got to do with PouchDB's call back to CouchDB.

Thanks

**Comment by bucktaylor** [comment] 2015-12-17 23:39
r.getErrorTypeByProp = function(e, t, n) {
            var o = r
              , s = Object.keys(o).filter(function(r) {
                var n = o[r];
                return "function" != typeof n && n[e] === t
            })
              , i = n && s.filter(function(e) {
                var t = o[e];
                return t.message === n
            })[0] || s[0];
            return i ? o[i] : null 
        }

When I debug this - the request (promise) returns this:

 e = "name", t = undefined, n = undefined

Any ideas?

**Comment by bucktaylor** [comment] 2015-12-18 16:56
SOLVED - hopefully this will help others.

OK - spent the morning trying to track this down: looks like several updates over the past week conspired to cause this issue. 

1). I could find no relation to the latest Linux distro update causing any issues, however the /boot directory was full, and the update was unable to complete the loading of several dependencies. Cleaned this up, and still got the error. As mentioned above, couchDb futon connected and worked locally as before issue.

2). So....looked at the error code and went back to network basics - response status was 0 - hmmm, means its not connecting at all....did a port scan and for some reason my router wasn't allowing the traffic to pass through the ports for couchDB!  So regarding status code 0: @nolanlawson  I added the following to your authentication code:

exports.ERR_CONNECTION_REFUSED = new PouchError({
    status: 0,
    error: 'err_connection_refused',
    reason: "Check to make sure firewall settings or access to couchDB port is correct."
});

3). Looked at my router configuration. The router was showing the ports configured for both TCP/UDP (which has been working previously for several months). Changed to just TCP and was able to connect. A scan now shows the ports as being open.

Now I could see the following error in chrome debugger: 

XMLHttpRequest cannot load https://www.my-website.com:1234/_session. Response to preflight request doesn't pass access control check: Credentials flag is 'true', but the 'Access-Control-Allow-Credentials' header is ''. It must be 'true' to allow credentials. Origin 'http://127.0.0.1:56960' is therefore not allowed access.

4). Went into couchDB - looked at the CORS section in configuration. I set the "credentials" to "true" and now it works! (previously this worked regardless of how I had this flag set....)

**Comment by singhketan** [comment] 2015-12-18 17:11
Doesn't work for me. I had cors enabled anyway. I have installed the latest version of CouchDB and it doesn't work. I tried upgrading pouchdb in the app as well but that didn't help either. I'll look into it this weekend and will get back.

**Comment by bucktaylor** [comment] 2015-12-18 19:07
Do you have "bind" set to 0.0.0.0 for the IP address?

**Comment by nolanlawson** [comment] 2015-12-20 18:23
Sweet! I'm going to close this, since it seems to have come down to faulty CORS/bind configuration.

Someone should make Youtube video or tutorial or something describing exactly how to set this up with a fresh CouchDB. These user errors occur far too frequently.

Out of curiosity, did you ever use https://github.com/pouchdb/add-cors-to-couchdb ? It sets `credentials` to true automatically.

**Closed by nolanlawson** 2015-12-20 18:23 UTC
Labels: help wanted
